name = "company-profile-simple1"
compatibility_date = "2024-08-26"
pages_build_output_dir = "./dist"

[env.production]
workers_dev = false

[env.staging]
workers_dev = true

[build]
command = "npm run build"
upload_dir = "dist"

[build.upload]
format = "directory"